config/routes.rb
Lab6::Application.routes.draw do
  get "welcome/index"
  resources :products do
    resources :comments
  end
  root to: "welcome#index"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController  
  def create
    @product = Product.find(params[:product_id])
    @comment = @product.comments.create(params[:comment].permit(:commenter, :body))
    redirect_to product_path(@product)
  end
  
  def destroy
    @product = Product.find(params[:product_id])
    @comment = @product.comments.find(params[:id])
    @comment.destroy
    redirect_to product_path(@product)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  def index
    @products = Product.all
  end
  
  def new
    @product = Product.new
  end
  
  def create  
    @product = Product.new(product_params)
    
    @product.save
      redirect_to @product
  end
  
  def show
    @product = Product.find(params[:id])
  end
  
  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    
    redirect_to products_path
  end
  
  private 
    def product_params
      params.require(:product).permit(:title,:description,:option,:category1,:category2)
    end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<% @product.comments.each do |comment| %>
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Delete comment', [comment.product, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

<% end %>

app/views/comments/_form.html.erb
<%= form_for([@product, @product.comments.build]) do |f| %>
  <p>
    <%= f.label :name %><br />
    <%=h f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :comment %><br />
    <%=h f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lab6</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/index.html.erb
<h1>Listing Products</h1>

<%= link_to 'Add new product', new_product_path %>

<table border=1>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Is it good?</th>
    <th>Category1</th>
    <th>Category2</th>
  </tr>

  <% @products.each do |product| %>
    <tr>
      <td><%= product.title %></td>
      <td><%= product.description %></td>
      <td><%= product.option %></td>
      <td><%= product.category1 %></td>
      <td><%= product.category2 %></td>
      <td><%= link_to 'Show', product %></td>
      <td><%= link_to 'Delete', product_path(product),
      method: :delete, data: { confirm: 'Are you sure' } %></td>
    </tr>
  <% end %>
</table>

app/views/products/new.html.erb
<h1>New Product</h1>
<%= form_for :product, url: products_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%=h f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%=h f.text_area :description, size:"30x6" %>
  </p>  
  <p>
    Is it good?
    <br>
    <%= f.label :radio1, "Yes" %>
    <%= f.radio_button :option, "Yes" %>
    <%= f.label :radio2, "No" %>
    <%= f.radio_button :option, "No" %>
    <%= f.label :radio3, "Ask my cat" %>
    <%= f.radio_button :option, "Ask my cat", :checked => true %>
  </p>  
  <p>
    <%= f.label :checkbox1, "Category 1" %>
    <%= f.check_box :category1 %>
    <%= f.label :checkbox2, "Category 2" %>
    <%= f.check_box :category2 %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>
 <% end %>
 
 <%= link_to 'Back', products_path %> 

app/views/products/show.html.erb
<p>
  <strong>Title:</strong>
  <%=h @product.title %>
</p>

<p>
  <strong>Description:</strong>
  <%=h @product.description %>
</p>

<p>
  <strong>Is it good?</strong>
  <%=h @product.option %>
</p>

<p>
  <strong>Category 1:</strong>
  <%=h @product.category1 %>
  <strong>Category 2:</strong>
  <%=h @product.category2 %>
</p>

<h2>Comments</h2>
<%= render "comments/comment" %>
<h2>Add a comment</h2>
<%= render "comments/form" %>
<%= link_to 'Back', products_path %>

app/views/welcome/index.html.erb
<h1>TIN-E Assignment 6</h1>
<%= link_to "'Glorious' rails app 'Products'", controller: "products" %>